# Builds static/img/spidey.svg and static/img/gwen.svg from one hand-made pixel grid
# (the upside-down hanging Spider-Man). Gwen is the same art, recoloured, with a hood trim and tip.
# N outline  R suit  B blue  . background  w web thread  e eye lens
SRC = """
...........N.N...........
..........NR.RN..........
.........NRR.RRN.........
........NRRR.RRRN........
......NNRRRR.RRRRNN......
.....NBRRRNN.NNRRRBN.....
....NBBBRNBB.BBNRBBBN....
...NBBBBNNN...NNNBBBBN...
...NBBBNRRRN.NRRRNBBBN...
....NNNRRRRNRNRRRRNNN....
......NRRBNRRRNBRRN......
.....NRRBNBRRRBNBRRN.....
.....NRRNBRRNRRBNRRN.....
......NRRRRRRRRRRRN......
.......NNRRNNNRRNN.......
.........NNRRRNN.........
........NRRRRRRRN........
.......NRRRRRRRRRN.......
......NRRRRRRRRRRRN......
......NRRNNRRRNNRRN......
......NRN..NRN..NRN......
......NRN.NRRRN.NRN......
......NRNNRRRRRNNRN......
......NRNRRRRRRRNRN......
......NRRRRRRRRRRRN......
......NRRRRRRRRRRRN......
.......NRRRRRRRRRN.......
........NNRRRRRNN........
..........NNNNN..........
""".strip().split("\n")
assert len({len(r) for r in SRC}) == 1
W, H0 = len(SRC[0]), len(SRC)
ROWS_TOTAL = H0

# --- tag cells: thread vs eyes vs transparent background -------------------------------
g = [list(r) for r in SRC]
for r in range(0, 9):                    # thread runs down the middle between the hands
    if g[r][12] == '.': g[r][12] = 'w'
for c in (11, 13):
    if g[7][c] == '.': g[7][c] = 'w'
seen, stack = set(), [(0, 0), (0, W - 1), (H0 - 1, 0), (H0 - 1, W - 1)]
while stack:                             # flood the outside; whatever '.' remains is an eye
    r, c = stack.pop()
    if (r, c) in seen or not (0 <= r < H0 and 0 <= c < W) or g[r][c] != '.': continue
    seen.add((r, c)); g[r][c] = ' '
    stack += [(r+1, c), (r-1, c), (r, c+1), (r, c-1)]
for r in range(H0):
    for c in range(W):
        if g[r][c] == '.': g[r][c] = 'e'

def grid(): return [row[:] for row in g]

# --- Gwen: hood trim + pointed tip ------------------------------------------------------
def gwenify(a):
    head = range(16, 28)
    def n4(r, c): return [(r+dr, c+dc) for dr, dc in ((1,0),(-1,0),(0,1),(0,-1))
                          if 0 <= r+dr < len(a) and 0 <= c+dc < W]
    outer = {(r, c) for r in range(len(a)) for c in range(W)
             if a[r][c] == 'N' and any(a[y][x] == ' ' for y, x in n4(r, c))}
    ring = [(r, c) for r in head for c in range(W)
            if a[r][c] == 'R' and any(p in outer for p in n4(r, c))]
    for r, c in ring:
        if r > 16: a[r][c] = 'T'         # 'T' = trim (black line just inside the hood edge)
    for r in head:                        # remaining head suit -> hood white
        for c in range(W):
            if a[r][c] == 'R': a[r][c] = 'H'
    # eye frames: the black outline hugging the lenses becomes pink, lenses stay white
    for r in range(H0):
        for c in range(W):
            if a[r][c] == 'N' and (r, c) not in outer and any(
                    0 <= r+dr < H0 and 0 <= c+dc < W and a[r+dr][c+dc] == 'e'
                    for dr in (-1, 0, 1) for dc in (-1, 0, 1)):
                a[r][c] = 'P'
    return a

PAL = {
  'spidey': {'N':'#05060a','R':'#e23636','B':'#3b66c4','w':'#cfd6ee','e':'#f4f6ff'},
  'gwen':   {'N':'#14121f','R':'#2a2640','B':'#ff6fa8','w':'#6b6f88','e':'#f6f7ff','P':'#ff6fa8','H':'#f6f7ff','T':'#14121f'},
}
for name in ('spidey', 'gwen'):
    a = gwenify(grid()) if name == 'gwen' else grid()
    C = PAL[name]
    rects = [f'<rect x="{x}" y="{y}" width="1" height="1" fill="{C[v]}"/>'
             for y, row in enumerate(a) for x, v in enumerate(row) if v != ' ']
    svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {ROWS_TOTAL}" '
           f'shape-rendering="crispEdges">' + ''.join(rects) + '</svg>')
    open(f'static/img/{name}.svg', 'w').write(svg)
